# -*- coding: utf-8 -*-
"""Linear_regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FBt4SJeyrpIMlXa8EHh2e-T7LMdyteL2
"""

import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

df = pd.read_csv("https://raw.githubusercontent.com/codebasics/py/master/ML/1_linear_reg/Exercise/canada_per_capita_income.csv")
df

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
plt.xlabel("year")
plt.ylabel("per capita income (US$)")
plt.scatter(df.year,df['per capita income (US$)'], color='red',marker='+')

reg = linear_model.LinearRegression()
reg.fit(df[['year']],df[['per capita income (US$)']])

reg.predict([[2020]])